pub mod acp_engine;
pub mod mode_selector;
pub mod relay;
pub mod team;
pub mod dedup;
pub mod memory;
pub mod output_sink;
pub mod persona;
pub mod prompt_builder;
pub mod registry;
pub mod roster;
pub mod selector;
pub mod slash;
pub mod traits;

pub use acp_engine::{AcpEngine, AcpEngineConfig};
pub use dedup::DedupStore;
pub use memory::{MemoryEvent, MemorySystem, MemoryTarget};
pub use output_sink::{throttled_stream, OutputSink};
pub use persona::AgentPersona;
pub use prompt_builder::SystemPromptBuilder;
pub use registry::{Session, SessionRegistry};
pub use roster::{AgentEntry, AgentRoster};
pub use selector::{EngineConfig, EngineSelector};
pub use slash::SlashCommand;
pub use traits::{AgentCtx, AgentEngine, BoxEngine, HistoryMsg};
